### ISSUE TITLE
Many Dependencies

### ISSUE THREAD

**Issue by ac360** [serverless/platform-sdk#3]
@eahefnawy Do you need all of the current dependencies?

**Comment by eahefnawy** [comment]
yeah I'm using them all. I should choose either `isomorphic-fetch` or `node-fetch` though, that was a mistake.

If size is a concern, I can probably find lightweight alternatives to some packages. What's your use case? are you including the `platform-sdk` in Lambda and worried about the package size?

**Comment by eahefnawy** [comment]
@ac360 I've cleared up our deps. Should be lighter now. What we have now is what we need.

**Comment by SalvatorePreviti** [comment]
core-js slows down loading and slows down NodeJS core objects adding polyfills serverless or plugins don't use at all.
Please, remove the dependency to babel-polyfill.

In our CI and locally, we don't run directly sls because is incredibly slow, but instead, we run a custom script that before running avoid loading core-js.

```javascript
global._babelPolyfill = true
if (!global.regeneratorRuntime) {
  global.regeneratorRuntime = require('regenerator-runtime')
}
require('serverless/bin/serverless')
```

[regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime) package is the only package actually needed.

May I suggest to remove `babel-polyfill` dependency and replace `require('babel-polyfill')` with `regenerator-runtime` ?

**Comment by astuyve** [comment]
Closed here https://github.com/serverless/platform-sdk/pull/62
